version: 2.1

executors:
  my-executor:
    docker:
      - image: amazon/aws-cli
    working_directory: /tmp

jobs:
  flow:
    executor: my-executor
    steps:
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run: mkdir -p workspace
      #- run: echo "Hello, world!" > workspace/echo-output
      - run: export FRONTEND_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=node-web-server" \
              --output text)
      - run: export API_URL="http://${FRONTEND_IP}:3000"
      - run: echo $API_URL > workspace/echo-output
      - run: cat workspace/echo-output
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output

  downstream:
    executor: my-executor
    steps:
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run: cat /tmp/workspace/echo-output
      # - run: |
      #     if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
      #       echo "It worked!";
      #     else
      #       echo "Nope!"; exit 1
      #     fi

workflows:
  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
